pasos_por_episodio: 100
numero_episodios: 5
politica: MultiInputPolicy
alpha1: 2.5
alpha2: 0.6
alpha3: 0.0001
alpha4: 0.1
sigma: 35
velocidad_blob: 40

load_weights: True
learn: True
weights_load_path: "model_weights/sac_alpha1_2.5_alpha2_0.6_alpha3_0.0001_sigma_35_numeps15"
weights_save_base_path: "model_weights"


