pasos_por_episodio: 40
numero_episodios: 25
politica: MultiInputPolicy
alpha1: 2.5
alpha2: 0.5
alpha3: 0.0001
sigma: 35

load_weights: True
weights_load_path: "model_weights/sac_alpha1_2.5_alpha2_0.5_sigma_35.zip"
weights_save_base_path: "model_weights"


